"""Add alert_conditions to Market model

Revision ID: 52a70b972725
Revises: 21176f54393a
Create Date: 2025-11-09 18:32:05.566178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52a70b972725'
down_revision = '21176f54393a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_conditions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('alert_conditions')

    # ### end Alembic commands ###
