"""Add do_not_disturb to User model

Revision ID: 77ebe013e432
Revises: 52a70b972725
Create Date: 2025-11-09 21:50:13.629637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ebe013e432'
down_revision = '52a70b972725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('do_not_disturb', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('do_not_disturb')

    # ### end Alembic commands ###
