"""baseline schema

Revision ID: 81fe5d2b22d6
Revises: 
Create Date: 2026-05-28 16:02:36.888153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fe5d2b22d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('nx', sa.Integer(), nullable=True),
    sa.Column('ny', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('alert_conditions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deletion_reason', sa.Text(), nullable=True),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('fcm_enabled', sa.Boolean(), nullable=True),
    sa.Column('fcm_topics', sa.JSON(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('do_not_disturb', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_date', sa.String(length=8), nullable=False),
    sa.Column('base_time', sa.String(length=4), nullable=False),
    sa.Column('fcst_date', sa.String(length=8), nullable=True),
    sa.Column('fcst_time', sa.String(length=4), nullable=True),
    sa.Column('nx', sa.Integer(), nullable=False),
    sa.Column('ny', sa.Integer(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('rain_1h', sa.Float(), nullable=True),
    sa.Column('east_west_wind', sa.Float(), nullable=True),
    sa.Column('north_south_wind', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('pop', sa.Float(), nullable=True),
    sa.Column('pty', sa.String(length=10), nullable=True),
    sa.Column('sky', sa.String(length=10), nullable=True),
    sa.Column('lightning', sa.String(length=10), nullable=True),
    sa.Column('sno', sa.Float(), nullable=True),
    sa.Column('api_type', sa.String(length=20), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.create_index('idx_weather_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_weather_lookup', ['nx', 'ny', 'base_date', 'base_time', 'api_type'], unique=False)

    op.create_table('damage_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('weather_event', sa.String(length=100), nullable=False),
    sa.Column('damage_level', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_recovery_time', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_alarm_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('alert_title', sa.String(length=200), nullable=False),
    sa.Column('alert_body', sa.Text(), nullable=False),
    sa.Column('total_users', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('weather_data', sa.JSON(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('rain_probability', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('precipitation_type', sa.String(length=20), nullable=True),
    sa.Column('forecast_time', sa.String(length=50), nullable=True),
    sa.Column('checked_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_verification_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_market_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notification_enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'market_id', name='unique_user_market')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_market_interests')
    op.drop_table('password_verification_attempts')
    op.drop_table('market_reports')
    op.drop_table('market_alarm_logs')
    op.drop_table('damage_statuses')
    with op.batch_alter_table('weather', schema=None) as batch_op:
        batch_op.drop_index('idx_weather_lookup')
        batch_op.drop_index('idx_weather_created_at')

    op.drop_table('weather')
    op.drop_table('users')
    op.drop_table('markets')
    # ### end Alembic commands ###
